ARG PANGEO_BASE_IMAGE_TAG=master
FROM pangeo/base-image:${PANGEO_BASE_IMAGE_TAG}

RUN pip install --upgrade pip

# Note: --no-deps avoids conflicts; --force-reinstall ensures fresh install
RUN pip install --no-cache-dir --force-reinstall --no-deps \
    git+https://github.com/auspatious/pyTMD.git@update-with-INATIDES-compatibility \
    git+https://github.com/piksel-ina/piksel-notebooks.git \
    dea-tools \
    https://github.com/auspatious/datacube-compute/releases/download/0.0.7/datacube_compute-0.0.7-cp312-cp312-linux_x86_64.whl