name: notebook
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pangeo-notebook=2025.07.15
  - python >=3.10
  - datacube ==1.9.6
  - boto3
  - scikit-learn >=1.5.0
  - openpyxl
  - dask-ml
  - pip
